/**
 * @file test.c
 * @author Prince Kumar (princekr3010gmail.com)
 * @brief This functon is responsible for testing.
 * @version 0.1
 * @date 2021-04-14
 * 
 * @copyright Copyright (c) 2021
 * 
 */
#include<stdio.h>
#include <stdlib.h>
#include "tic-tac-toe.h"
#include "..\unity\unity.h"


/// Setup function for Unity.
void setUp(){}
/// tearDown funtion for Unity.
void tearDown(){}

/**
 * @brief This function testing the chech funtion.
 * 
 */
void result(void){
TEST_ASSERT_EQUAL_CHAR(' ', check());
}

/**
 * @brief Checking weather game board is initillized or not.
 * 
 */
void game_board_init(void){
    TEST_ASSERT_EQUAL_INT16(1, init_matrix());
}

/**
 * @brief Checking weather game board is Displayed or not.
 * 
 */
void display_board(void){
    TEST_ASSERT_EQUAL_INT16(1, disp_matrix());
}

/**
 * @brief Testing valid move generated by computer or not.
 * 
 */
void Test_computer_move(void){
    TEST_ASSERT_EQUAL_INT16(1, get_computer_move());
}

/**
 * @brief This function run the complete game and check weather every module runs fine.
 * 
 */
/*void Test_complete_game(void){
    TEST_ASSERT_EQUAL_INT16(1, game());
}*/

int main(){

/// UNITY_BEGIN funtion for unty.
    UNITY_BEGIN();

/// testing game board initillization.
    printf("***************Checking weather game board initlizied or not***************************\n\n");
    RUN_TEST(game_board_init);
    printf("\n");
/// Testing game result
     printf("***********************************Checking Result************************************\n\n");   
    RUN_TEST(result);
    printf("\n");
/// Testing game board display.
     printf("***********************************Display Game Board************************************\n\n");  
    RUN_TEST(display_board);
    printf("\n");
    printf("***********************************Checking Computer Move************************************\n\n");  
/// Testing computer move. 
    RUN_TEST(Test_computer_move);
    printf("\n");
/// Tesing Complete game.
  //  printf("***********************************Testing Complete game************************************\n\n");  
   // RUN_TEST(Test_complete_game);
    //printf("\n");

   

    return UNITY_END();

}